name: JulianPlugin
version: 0.3.1
author: Julian Lee
api-version: 1.13
main: me.lazward.julianplugin.JulianPlugin
commands:
   chatas:
      description: Message as another person.
   ticks:
      description: Return the world's total number of ticks.
   ci:
      description: Custom item
   wolf:
      description: Get wolf owner
   horse:
      description: Get horse owner